services:
  swbotapi:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PATH=/opt/conda/envs/swLorebot/bin:$PATH
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [compute, utility, gpu]
    runtime: nvidia
    entrypoint:
      [
        "sh",
        "-c",
        "/opt/conda/bin/activate swLorebot && python swBotAPI_Runpod.py"
      ]
